window.__justep.__ResourceEngine.loadCss([{url: '/UI2/v_02c42872592d4fc3aa9d968dbd4f5f38l_zh_CNs_d_m/system/components/bootstrap.min.css', include: '$model/UI2/system/components/bootstrap/lib/css/bootstrap,$model/UI2/system/components/bootstrap/lib/css/bootstrap-theme'},{url: '/UI2/v_d9ff8e260ee34caab2443b3fe493ece1l_zh_CNs_d_m/system/components/comp.min.css', include: '$model/UI2/system/components/justep/lib/css2/dataControl,$model/UI2/system/components/justep/input/css/datePickerPC,$model/UI2/system/components/justep/messageDialog/css/messageDialog,$model/UI2/system/components/justep/lib/css3/round,$model/UI2/system/components/justep/input/css/datePicker,$model/UI2/system/components/justep/row/css/row,$model/UI2/system/components/justep/attachment/css/attachment,$model/UI2/system/components/justep/barcode/css/barcodeImage,$model/UI2/system/components/bootstrap/dropdown/css/dropdown,$model/UI2/system/components/justep/dataTables/css/dataTables,$model/UI2/system/components/justep/contents/css/contents,$model/UI2/system/components/justep/common/css/forms,$model/UI2/system/components/justep/locker/css/locker,$model/UI2/system/components/justep/menu/css/menu,$model/UI2/system/components/justep/scrollView/css/scrollView,$model/UI2/system/components/justep/loadingBar/loadingBar,$model/UI2/system/components/justep/dialog/css/dialog,$model/UI2/system/components/justep/bar/css/bar,$model/UI2/system/components/justep/popMenu/css/popMenu,$model/UI2/system/components/justep/lib/css/icons,$model/UI2/system/components/justep/lib/css4/e-commerce,$model/UI2/system/components/justep/toolBar/css/toolBar,$model/UI2/system/components/justep/popOver/css/popOver,$model/UI2/system/components/justep/panel/css/panel,$model/UI2/system/components/bootstrap/carousel/css/carousel,$model/UI2/system/components/justep/wing/css/wing,$model/UI2/system/components/bootstrap/scrollSpy/css/scrollSpy,$model/UI2/system/components/justep/titleBar/css/titleBar,$model/UI2/system/components/justep/lib/css1/linear,$model/UI2/system/components/justep/numberSelect/css/numberList,$model/UI2/system/components/justep/list/css/list,$model/UI2/system/components/justep/dataTables/css/dataTables'}]);window.__justep.__ResourceEngine.loadJs(['/v_c00e91d83f9c41c7a92432f5ba7598c2l_zh_CNs_d_m/system/core.min.js','/v_e5d3ae9add9b4333b294ca0dc1974c4cl_zh_CNs_d_m/system/common.min.js','/v_2c009ff5d6774cf7af9fa6f96b785a8bl_zh_CNs_d_m/system/components/comp.min.js']);define(function(require){
require('$model/UI2/system/components/justep/model/model');
require('$model/UI2/system/components/justep/loadingBar/loadingBar');
require('$model/UI2/system/components/justep/button/button');
require('$model/UI2/system/components/justep/controlGroup/controlGroup');
require('$model/UI2/system/components/justep/titleBar/titleBar');
require('$model/UI2/system/components/justep/panel/child');
require('$model/UI2/system/components/justep/data/data');
require('$model/UI2/system/components/justep/window/window');
require('$model/UI2/system/components/justep/panel/panel');
var __parent1=require('$model/UI2/system/lib/base/modelBase'); 
var __parent0=require('$model/UI2/zmt/slaughterInspection/regFarmers/regFarmers'); 
var __result = __parent1._extend(__parent0).extend({
	constructor:function(contextUrl){
	this.__sysParam='true';
	this.__contextUrl=contextUrl;
	this.__id='';
	this.__cid='cbQJJfe';
	this._flag_='8c22d8afa519ce0b51bff2b83a5fe29f';
	this._wCfg_={};
	this._appCfg_={};
	this.callParent(contextUrl);
 var __Data__ = require("$UI/system/components/justep/data/data");new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"address":{"define":"address","label":"地址","name":"address","relation":"address","type":"String"},"createrId":{"define":"createrId","label":"创建人ID","name":"createrId","relation":"createrId","type":"String"},"createrName":{"define":"createrName","label":"创建人名称","name":"createrName","relation":"createrName","type":"String"},"farmerName":{"define":"farmerName","label":"养殖户姓名","name":"farmerName","relation":"farmerName","type":"String"},"feedName":{"define":"feedName","label":"饲料名称","name":"feedName","relation":"feedName","type":"String"},"id":{"define":"id","label":"ID","name":"id","relation":"id","type":"String"},"password":{"define":"password","label":"密码","name":"password","relation":"password","type":"String"},"phone":{"define":"phone","label":"联系电话","name":"phone","relation":"phone","type":"String"},"typeId":{"define":"typeId","label":"类型ID","name":"typeId","relation":"typeId","type":"String"},"typeName":{"define":"typeName","label":"类型名称","name":"typeName","relation":"typeName","type":"String"}},"directDelete":false,"events":{},"idColumn":"id","isMain":false,"limit":20,"xid":"regFarmersData"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"createrId":{"define":"createrId","label":"创建人ID","name":"createrId","relation":"createrId","type":"String"},"createrName":{"define":"createrName","label":"创建人姓名","name":"createrName","relation":"createrName","type":"String"}},"directDelete":false,"events":{},"idColumn":"createrId","isMain":false,"limit":20,"xid":"createrData"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"typeId":{"define":"typeId","label":"类型ID","name":"typeId","relation":"typeId","type":"String"},"typeName":{"define":"typeName","label":"类型名称","name":"typeName","relation":"typeName","type":"String"}},"directDelete":false,"events":{},"idColumn":"typeId","isMain":false,"limit":20,"xid":"typeData"});
}}); 
return __result;});
